# Generated by Django 2.2.9 on 2020-02-13 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200213_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='brands',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='img',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='brands',
            name='is_instock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brands',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='brands',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Products'),
        ),
        migrations.DeleteModel(
            name='Liqs',
        ),
    ]
