# Generated by Django 2.2.9 on 2020-02-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200216_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Products'),
        ),
    ]
